### ISSUE TITLE
Make user login/password reset case-insensitive

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring-localauth#6]
The email address on the login and password reset forms is case-sensitive (this is also the case in the old AT).

We get a number of support requests each month caused by users not expecting this and being unable to login.

In the past we said it was difficult to introduce this as there may already be some ATs set up with users whose email addresses would clash if we suddenly treated them as case insensitive (eg bob@example.com and Bob@example.com). 

As this is a clean slate I think this would be a really good opportunity to make the user email case insensitive. 

We would need to modify:
- Login form 
- Password reset form
- When creating a user check that case-insensitive email is unique
- When updating a user check that case-insensitive email is unique

**Comment by kineopete** [comment]
Not fixed on 1.0.0-rc.2 - capitalised usernames (as either title case or all caps) aren't validated.

**Comment by taylortom** [comment]
Was missing a fix for queries - have added.

**Comment by joe-allen-89** [comment]
Fixed, new user stored as lower and able to login with/without capitalisation.
